### ISSUE TITLE
Criação de pacotes

### ISSUE THREAD

**Issue by felipe-felizardo** [felipe-felizardo/kanboard#4]
**ANÁLISE**

**Usuários com privilégio podem criar pacotes com antecedências:**
- [x] Usuário com privilégio de "Gerente" (analista de negócios) criar o projeto (sprint / pacote)
- [x] Nas configurações do projeto, deve adicionar seu grupo (time), e colocar como gerente de projeto o analista de sistemas
- [x] Neste momento a sprint / pacote poderá importar solicitações

**As solicitações devem ser importadas da intranet**
- [x] Importar Id da solicitação
- [x] Importar _Tipo de solicitação_ como raia (swimlane) #3 
- [x] Importar _Classificação_ com categoria (category) #3 
- [x] Importar código e nome do cliente da solicitação #23 
* As APIs utilizadas para importar os dados da intranet são:
    * ***createTask*** (criar uma task)
    * ***createExternalTaskLink*** (link dos arquivos anexados)
    * ***createComment*** (comentários)
    * ***saveTaskMetadata*** ? (metadata de campos que não existem no BD)
- [ ] Unificar estes quatro métodos de importação em apenas um método

**Fechamento de pacotes / sprints**
- [x] Deverá ter um campo numérico no cadastro de projeto indicando o limite de horas #7 
- [x] Deverá ter um campo na tabela de projeto para especificar o limite de horas #7
- [x] O projeto só poderá ser fechado, caso as horas orçadas nas tarefas não ultrapassem o limite de horas #7
- [x] Solicitações só poderão ser importadas para o pacote **fechado** pelo gerente de projeto #7
- [x] O projeto deverá ter um indicador de que está com o escopo aberto ou fechado #7
